### ISSUE TITLE
Fails with Parallel::ForkManager 1.08 and later

### ISSUE THREAD

**Issue by eserte** [fujiwara/p5-Parallel-Benchmark#1]
See http://analysis.cpantesters.org/reports_by_field?distv=Parallel-Benchmark-0.08;field=mod%3AParallel%3A%3AForkManager for an analysis of fail/pass reports compared with the Parallel::ForkManager version. Currently there are no PASS reports with Parallel::ForkManager 1.08 and later.

**Comment by fujiwara** [comment]
Thanks for reporting.
I fixed a problem with P::FM(>=1.08) and released 0.09!

**Comment by eserte** [comment]
There are still fails with 0.09. Looks now that it's fine with Parallel::ForkManager 1.12, but fails with older versions. See: 
http://analysis.cpantesters.org/reports_by_field?distv=Parallel-Benchmark-0.09;field=mod%3AParallel%3A%3AForkManager

**Comment by fujiwara** [comment]
oh.. I made a mistake the dependency. fixed and relasesed 0.10. Thanks a lot.

**Comment by eserte** [comment]
Looks good now.
